CREATE TABLE STUDENT(
STUDENT_NO NUMBER PRIMARY KEY,
NAME VARCHAR2(20) NOT NULL,
ADDRESS VARCHAR2(100)
);


------------------------------------
INSERT INTO STUDENT VALUES(1,'유재석','서울시 서초구');
INSERT INTO STUDENT VALUES(2,'지석진','부산시 영도구');
INSERT INTO STUDENT VALUES(3,'하하',null);
INSERT INTO STUDENT VALUES(4,'송지효','일산시');
INSERT INTO STUDENT VALUES(5,'양세찬','서울시 중구');


DELETE FROM STUDENT WHERE NAME = '양세찬';

--------------------------------------
UPDATE STUDENT SET ADDRESS = '김포시' WHERE STUDENT_NO = 4;


---------------------------------------
ALTER TABLE STUDENT ADD (ENTRANCE_DATE DATE DEFAULT SYSDATE NOT NULL);

----------------------------------------
CREATE TABLE MEMBER (
ID VARCHAR2(10) PRIMARY KEY,
PASSWORD VARCHAR2(20) NOT NULL,
NICKNAME VARCHAR2(50)
);

CREATE TABLE BOARD (
BOARD_NO NUMBER PRIMARY KEY,
ID VARCHAR2(10) NOT NULL,
CONSTRAINT FK_ID FOREIGN KEY(ID) REFERENCES MEMBER(ID),
TITLE VARCHAR2(50) NOT NULL,
CONTENT VARCHAR2(200) NOT NULL
);

---------------------------------------------------
INSERT INTO MEMBER VALUES('you', '1234', '재석유');
INSERT INTO MEMBER VALUES('ji', '1234', '지석진');
INSERT INTO MEMBER VALUES('ha', '1234', '하하');
INSERT INTO MEMBER VALUES('song', '1234', '송지효');

INSERT INTO BOARD VALUES(1, 'you', '제목입니다', '내용입니다');
INSERT INTO BOARD VALUES(2, 'you', '제목입니다', '내용입니다');
INSERT INTO BOARD VALUES(3, 'song', '제목입니다', '내용입니다');
